# vim: noai:ts=2:sw=2:expandtab
---
# file dev
- hosts: localhost
  tasks:
    - name: Install aufs
      apt: name={{item}}
      with_items:
        - linux-image-extra-{{ansible_kernel}}
        - aufs-tools
    - name: Install Docker
      get_url: url=https://get.docker.com/ubuntu/ dest=/tmp/setup-docker.sh mode=0755
      register: result
    - apt: name=python-pip
    - pip: name=docker-py
    - shell: /tmp/setup-docker.sh
      when: result|success
    - name: Install fig
      shell: curl -L https://github.com/docker/fig/releases/download/1.0.1/fig-`uname -s`-`uname -m` > /usr/local/bin/fig && chmod +x /usr/local/bin/fig
      args:
          creates: /usr/local/bin/fig
    - name: run consul
      docker: image=progrium/consul name="consul" hostname="consul" ports="8400:8400, 8500:8500, 8600:53/udp" command="-server -bootstrap -ui-dir /ui" state=running
    - name: run shipyard
      command:  docker run --rm -v /var/run/docker.sock:/var/run/docker.sock shipyard/deploy start && touch /home/vagrant/shipyard.done
      args:
          creates: /home/vagrant/shipyard.done
    - name: install nsenter
      command: docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter creates=/usr/local/bin/docker-enter
    - name: run registrator
      docker: image=progrium/registrator volumes="/var/run/docker.sock:/tmp/docker.sock" command="consul://10.0.2.15:8500"
    - name: run docker registry
      docker: image=registry ports="5000:5000" volumes="/opt/docker-registry:/tmp/registry"
    - name: add vagrant to docker group
      user: name=vagrant groups=docker append=yes
